### ISSUE TITLE
TypeError: Cannot read property 'ENV' of undefined

### ISSUE THREAD

**Issue by Shaphil** [evodeck/angular-linkedin-sdk#1]
I was just trying to run the demo application provided. On 'Get API key from SDK' button click the following error was generated:

```
ERROR TypeError: Cannot read property 'ENV' of undefined    AppComponent.html:11 
    at AppComponent.webpackJsonp.171.AppComponent.getApiKeyFromSdkIN (app.component.ts:88)
    at Object.eval [as handleEvent] (AppComponent.html:11)
    at handleEvent (core.es5.js:11826)
    at callWithDebugContext (core.es5.js:13041)
    at Object.debugHandleEvent [as handleEvent] (core.es5.js:12629)
    at dispatchEvent (core.es5.js:8777)
    at core.es5.js:9369
    at HTMLButtonElement.<anonymous> (platform-browser.es5.js:2683)
    at ZoneDelegate.webpackJsonp.553.ZoneDelegate.invokeTask (zone.js:414)
    at Object.onInvokeTask (core.es5.js:4117)
```

Please note that, I did: 

- `npm install angular-linkedin-sdk --save`
- and then replaced the import statements to 
`import { LinkedInSdkModule } from 'angular-linkedin-sdk';`
from `import { LinkedInSdkModule } from '../../temp';`
in `app.module.ts`
- and `import { LinkedInService } from 'angular-linkedin-sdk';`
from `import { LinkedInService } from '../../temp';`
in `app.component.ts`

**Comment by sirwalt** [comment]
Unfortunately a "last-minute" fix from 05/05/2017 that was to keep compatibility with Angular 2 was skipping the entire initialization of the LinkedIn SDK. Version 0.1.5 fixed this issue.

Please note:

- You must provide your own LinkedIn API Key in app.module.ts
- The initialization of the LinkedIN SDK must complete prior to calls to getSdkIN() to get a valid reference to the SDK. The demo doesn't take this into account yet, but you could use code like below, if you need to access the native LinkedIN SDK within component or service initialization.

`this.linkedInService.isInitialized$.filter((value)=>value === true).take(1).switchMap(()=>{
   let nativeSdkRef = this.linkedInService.getSdkIN();
   // your code accessing native SDK here
});`

**Comment by Shaphil** [comment]
Thank you, upgraded to version 0.1.5 and the problem was solved.
