### ISSUE TITLE
Possibility to retrieve the access token

### ISSUE THREAD

**Issue by SimoneCafiero** [evodeck/angular-linkedin-sdk#4]
Hi guys,
is there a way to retrieve the access token? I tried exploring the **linkedInService.getSdkIN().ENV** but there is just the oauth one.

Thanks

**Comment by Gustavo-Jordao** [comment]
Hey there,
we can see the anonymous access token in the ENV property. Could be an issue with the LinkedIN API, have you configured your application on their platform correctly?

![token](https://cloud.githubusercontent.com/assets/26542523/26300315/a3b7e58a-3ed5-11e7-90a3-d6343f4d4793.png)

**Comment by SimoneCafiero** [comment]
Hi Gustavo,
thanks for your reply. If I try to validate the **anonymous_token** through the LinkedinAPI I get a **401 Invalid access token** error.

Here are the endpoints I use to validate the token:

GET `https://api.linkedin.com/v1/people/~?oauth2_access_token=<TOKEN_HERE>` as it is


PUT/POST/ `https://api.linkedin.com/v1/people/~` with a Header with Authorization Bearer <TOKEN>

**Comment by sirwalt** [comment]
Hi Simone,

please note that we can not give support for the official LinkedIn SDK itself. But let me try to help anyways.

Unfortunately LinkedIn stopped support for many of their APIs and useful links are dead. This is not limited to the JS SDK. So far they just want to continue support for their development partners and you have to apply for such a program to get further support.

According to your specific problem there were a lot of threads as well as libraries out there to exchange the client OAuth token with a long living one to use on REST API. Unfortunately this support seams to also been stoped.

Google result on token exchange:
https://www.google.de/search?q=linkedin+exchange+token&oq=linkedin+exchange+token

And here is latest post on stackoverflow according to this topic:
https://stackoverflow.com/questions/31226310/where-to-find-the-oauth-token-and-secret-in-the-linkedin-application

Cheers Walter

**Comment by SimoneCafiero** [comment]
Hi Walter,
thanks for sharing the info.

As a 'angular-linkedin-sdk' user, which are your guidelines for ensuring that the retrieved info are valid supposing that you want to store that info in your internal DB?

Best,
S

**Comment by Gustavo-Jordao** [comment]
Hey Simone,
as Walter mentioned this project is just a Wrapper for the SDK itself, if LinkedIN is no longer supporting the authorisation token exchange you should try to ask this question in Stackoverflow or similar for further help.
I'll mark this issue as solved since it is no longer a bug.

Thank you for your feedback.
